server:
  port: 8001

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: cloud-provider-payment-sentinel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.128:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: FN5HW5Y1XQJ742I7
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.71.128:8848
    sentinel:
      transport:
        dashboard: 192.168.71.128:8080
      eager: true
      datasource:
        ds:
          nacos:
            server-addr: 192.168.71.128:8848
            namespace: 915b8d64-e88c-4d1a-b7ac-36f2f6df34ce
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-id: payment-sentinel-flow-rules
            data-type: json

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities

management:
  endpoints:
    web:
      exposure:
        include: '*'
