server:
  port: 8000

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.71.129:8848

service:
  payment: http://cloud-provider-payment