server:
  port: 8010

spring:
  application:
    name: cloud-seata-account
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.128:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: FN5HW5Y1XQJ742I7
  cloud:
    alibaba:
      seata:
        tx-service-group: tx_group
    nacos:
      discovery:
        server-addr: 192.168.71.128:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities

management:
  endpoints:
    web:
      exposure:
        include: '*'

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      cloud-seata-account-group: default
  registry:
    type: nacos
    nacos:
      namespace: b9c753fe-56e5-48f1-ad10-0349e0ca3b11
      serverAddr: 192.168.71.128:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos